### ISSUE TITLE
Fix `install_requires` argument in setup.py

### ISSUE THREAD

**Issue by zdelrosario** [zdelrosario/py_grama#129]
As of now, we're relying on a user to install packages following `requirements.txt`. Should incorporate these packages into `install_requires` argument for pip to make installation easier. See [this](https://packaging.python.org/discussions/install-requires-vs-requirements/) for more info.

**Comment by mstites** [comment]
Can we close this issue?

**Comment by zdelrosario** [comment]
Yes! Thanks for catching this....
